from django.conf.urls import url
from basic import views

urlpatterns = [
    url(r'^$', views.HomePageView.as_view(), name="index"),
    url(r"^about-us/$", views.AboutUsView.as_view(), name="about-us"),
    url(r"^mission-and-vision/$", views.MissionAndVision.as_view(), name="mission-and-vision"),
    url(r"^school-profile/$", views.SchoolProfileView.as_view(), name="school-profile"),
    url(r"^management-committee/page-2/$", views.ManagementCommitteeView.as_view(), name="management-committee"),
    url(r"^management-committee/page-3/$", views.ManagementCommitteeView.as_view(), name="management-committee"),
    url(r"^management-committee/$", views.ManagementCommitteeView.as_view(), name="management-committee"),
    url(r"^admission/$", views.AdmissionView.as_view(), name="admission"),
    url(r"^rules-and-regulations/$", views.RulesAndRegulations.as_view(), name="rules-and-regulations"),
    url(r"^syllabus/$", views.SyllabusView.as_view(), name="syllabus"),
    url(r"^facilities/$", views.FacilitiesView.as_view(), name="facilities"),
    url(r"^examinations/$", views.ExaminationsView.as_view(), name="examinations"),
    url(r"^results/$", views.ResultsView.as_view(), name="results"),
    url(r"^library/$", views.LibraryView.as_view(), name="library"),
    url(r"^labs/$", views.labsView.as_view(), name="labs"),
    url(r"^image-gallery/$", views.ImageGallery.as_view(), name="image-gallery"),
    url(r"^video-gallery/$", views.VideoGallery.as_view(), name="video-gallery"),
    url(r"^admission-enquiry/$", views.AdmissionEnquiryView.as_view(), name="admission-enquiry"),
    url(r"^notice-board/$", views.NoticeBoardView.as_view(), name="notice-board"),
    url(r"^student-details/$", views.StudentDetailsView.as_view(), name="student-details"),
    url(r"^contact-us/$", views.ContactUsView.as_view(), name="contact-us"),
    url(r"^fee-rules/$", views.FeeRulesView.as_view(), name="fee-rules"),
    url(r"^disiplinary-rules/$", views.DisiplinaryRulesView.as_view(), name="disiplinary-rules"),
    url(r"^events/$", views.EventsView.as_view(), name="events"),
    url(r"^news-and-updates/$", views.NewsAndUpdatesView.as_view(), name="news-and-updates"),
    url(r"^calender/$", views.CalenderView.as_view(), name="calender"),
    url(r"^privacy-policy/$", views.PrivacyPolicyView.as_view(), name="privacy-policy"),
    url(r"^terms-of-use/$", views.TermsOfUseView.as_view(), name="terms-of-use"),
    url(r"^sitemap/$", views.Sitemap.as_view(), name="sitemap"),
]
